.github/workflows/semantic_pull_request.yml
- Add semantic pull request workflow to enable [Add PR Title is Conventional Job](https://github.com/input-output-hk/catalyst-voices/issues/16) for Catalyst Voices
=> feat(workflows): Add Semantic Pull Request

.envrc, .gitignore, flake.lock, flake.nix
=> build: migrates from std to devenv

actions/discover/dist/index.js, actions/discover/src/discover.ts, actions/discover/src/index.test.ts
- fix: corrects binary name in discover action
- chore: fixes formatting
- chore: removes old comment
=> fix: corrects binary name in discover action

earthly/rust/Earthfile, earthly/rust/Readme.md, earthly/rust/config.toml, earthly/rust/example/rust-toolchain.toml
Ready to go.
I have a test release tagged against this, which I am using to test the Earthly Rust build in Cat Voices.
As soon as this merges, I will delete it, re-tag an official release with this and update the cat-voices rust earthly to point to the correct ci version.
=> feat: Rust builder setup

earthly/postgresql/Earthfile, earthly/postgresql/Readme.md
During applying this PostgreSQL builder for event-db in catalyst-voices, I have found few issues in this earthly file. Fixed it.
Updated README.md
=> fix: Fix PostgreSQL earthly file, update Readme

.github/workflows/branch-delete-cleanup.yml, .github/workflows/branch-pages-delete.yml, .github/workflows/pages.yml, docs/src/guides/docs.md
Try and fix branch doc deletion
=> feat(docs): Fix branch deletion

.github/ISSUE_TEMPLATE/EPIC.yml, .github/ISSUE_TEMPLATE/TASK.yml, .github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.yml, .github/pull_request_template.md, CONTRIBUTING.md
=> fear: add issue templates

docs/mkdocs.yml, docs/src/architecture/01_introduction_and_goals.md, docs/src/architecture/02_architecture_constraints.md, docs/src/architecture/03_system_scope_and_context.md, docs/src/architecture/04_solution_strategy.md, docs/src/architecture/05_building_block_view.md, docs/src/architecture/06_runtime_view.md, docs/src/architecture/07_deployment_view.md, docs/src/architecture/08_concepts.md, docs/src/architecture/09_architecture_decisions/0001-arch-std.md, docs/src/architecture/09_architecture_decisions/0002-adr.md, docs/src/architecture/09_architecture_decisions/index.md, docs/src/architecture/09_architecture_decisions/template/.pages, docs/src/architecture/09_architecture_decisions/template/0xxx-template.md_, docs/src/architecture/10_quality_requirements.md, docs/src/architecture/11_technical_risks.md, docs/src/architecture/12_glossary.md, docs/src/architecture/index.md
Update architecture docs with icons.
Add first real ADRs
=> docs(docs): Update architecture docs with icons and add first real ADRs

.github/workflows/ci.yml, .github/workflows/publish.yml, actions/push/README.md, actions/push/dist/index.js, actions/push/src/push.test.ts, actions/push/src/push.ts
=> feat: allow skipping publishing when pushing to default

.github/workflows/semantic_pull_request.yml
- Enable PR title validation CI job
=> feat: PR title validation CI job run

.github/workflows/ci.yml, .github/workflows/publish.yml, docs/src/reference/workflows.md
=> feat: allows overwriting the default branch of a repository

earthly/rust/scripts/std_build.sh, examples/rust/Cargo.lock, examples/rust/crates/bar/src/lib.rs
- Fixed std_build.sh script bug
- Fixed Rust example project listing
> e.g., Closes #131
=> fix: Rust std_build.sh script bug

.github/workflows/release.yml
=> fix: fixes release artifact collection

.github/workflows/dogfood.yml
Change dogfood ci cli version to v2.2.0
=> fix: change ci cli version of dog food

.github/workflows/dogfood.yml
Update CI CLI version to v2.2.1
=> fix: update ci cli version

tools/fetcher/pkg/artifact.go, tools/fetcher/pkg/artifact_test.go
=> fix(fetcher): corrects filename used when specifying a version

actions/setup/action.yml
=> fix: moves docker login to first step in setup action to increase API rate limit

actions/install/action.yml, actions/install/dist/index.js, actions/install/src/install.test.ts, actions/install/src/install.ts
=> feat: modifies install action to allow installing other released binaries

.github/workflows/run.yml, actions/setup/action.yml
=> feat: adds support for installing updater in setup action

.github/workflows/deploy.yml
=> fix: uses correct CUE version

docs/src/reference/workflows.md
=> docs: updates deploy workflow docs

services/jorm-metrics-server/deployment.yml
=> fix: corrects jorm-metrics-server deployment file

.config/dictionaries/project.dic, services/jorm-metrics-server/jorm_metrics_server/client.py, services/jorm-metrics-server/jorm_metrics_server/metrics/proposal_votes.py, services/jorm-metrics-server/jorm_metrics_server/models/voter.py
=> feat: adds proposal total voting power to jorm-metrics-server

utilities/scripts/python/diff.py, utilities/scripts/python/vendor_files_check.py
Fixed some minor issue which affects on the correct representation of the tool diff checks
=> fix: Fixed `toml_diff_check` printing, `diff._strict_diff_ .change_flags()` function

.config/dictionaries/project.dic, earthly/rust/Earthfile, earthly/wasm/c/Earthfile, earthly/wasm/c/scripts/std_build.py, examples/wasm/c/Earthfile, examples/wasm/c/component.c, examples/wasm/c/demo.wit
Add a base setup script for C WASI compiler
[#117](https://github.com/input-output-hk/hermes/issues/117)
* Added base
=> feat(wasm): C base

cspell.json
=> build(cspell): dict

earthly/rust/stdcfgs/deny.toml, examples/rust/deny.toml, utilities/dbviz/deny.toml
Add CC0-01 license in deny toml
=> fix: add cc0-1 license to rust std config

earthly/rust/Earthfile
=> fix: update rust tool

.github/workflows/pages.yml
This PR fixes an issue with multiline variables in github
List the issue numbers related to this pull request
=> fix: multiline github env

.github/workflows/branch-pages-delete.yml
Fixes this [error](https://github.com/input-output-hk/catalyst-ci/actions/runs/8393668446/job/22989149908#step:5:24) in the delete pages github workflow restoring the checkout action
=> fix: restore checkout action

.github/workflows/ci.yml, earthly/mithril_snapshot/Earthfile, earthly/rust/Earthfile
- Added mithril snapshot `preview` artifact
- fixed `refinery` tool, bumped version.
=> feat: Add mithril preview snapshot artifact, fixed rust builder

earthly/mithril_snapshot/Earthfile
- Saved artifact as a directory
- Added `preprod` snapshot
=> feat: Update how mithril snapshot is packaged, added `preprod` snapshot

cspell.json, earthly/rust/Earthfile
=> feat: update cspell

earthly/mithril_snapshot/Earthfile
- Updated preprod mithril snapshot.
- removed redundant preview snapshot loading.
=> feat: Update preprod snapshot

earthly/mdlint/Earthfile
This PR fixes the mdlint target 
=> fix: Mdlint earthly target

earthly/mithril_snapshot/Earthfile
=> fix(mithril): Update to latest preprod snapshot as older one no longer available.

cli/Earthfile, docs/src/appendix/earthly.md, docs/src/guides/languages/go.md, earthly/go/Earthfile, examples/go/Earthfile, tools/fetcher/Earthfile, tools/updater/Earthfile
Always install Ginkgo,  and bump GO version to latest.
=> fix(go): Always install ginkgo and bump go version

earthly/rust/stdcfgs/deny.toml, examples/rust/deny.toml, utilities/dbviz/deny.toml
* Add 'MPL-2.0' to allow list
* Remove ban for 'windows' crate
* Add 'licenses.clarify' for 'ring' crate in deny.toml
* Add 'MPL-2.0' to allow list
* Remove ban for 'windows' crate
* Add 'licenses.clarify' for 'ring' crate in deny.toml
=> fix(rust): Update licenses

earthly/flutter/installer/Earthfile
- Update Firefox ESR version to `115.12.0esr-1~deb12u1` because previous one was removed(?)
=> fix:  firefox esr version

cli/Earthfile, earthly/flutter/Earthfile, earthly/flutter/installer/Earthfile
- Disable flutter analytics
- Fix text color in installer
- Remove pre dependency installation in Chrome installation
=> fix: flutter ci

earthly/flutter/Earthfile
Adds a reusable function that validates if all publishable packages can be published without issues.
The function will be run in catalyst_voices for every PR to ensure the packages are not ending up in a broken state.
=> feat: add publish dry run earthly script

earthly/flutter/Earthfile
Replaces missing chromium version.
=> fix: missing chromium version

.github/workflows/pages.yml
fix nightly ci error when run pushing action
=> fix: add nightly folder to gh-pages

.github/workflows/pages.yml
Remove a line that was introduced by mistake
=> fix: removes unneeded line

earthly/mithril_snapshot/Earthfile
This PR updates the preprod mithril snapshot digest because the previous one wasnt working anymore
=> fix: update mithril snapshot

earthly/flutter/Earthfile
Adding coverage_combine tool to combine flutter packages coverage reports
=> feat: adds flutter coverage tool

earthly/flutter/Earthfile, examples/flutter/example/ios/Runner/AppDelegate.swift, examples/flutter/example/macos/Runner/AppDelegate.swift, examples/flutter/example/pubspec.lock, examples/flutter/example/pubspec.yaml, examples/flutter/example/web/index.html
- upgrade flutter to 3.24.1
- upgrade dart to 3.5.0
- upgrades dependencies and migrates deprecated code in example app
=> chore: upgrade flutter to 3.24.1 and dart to 3.5.0

earthly/flutter/Earthfile, examples/flutter/example/Earthfile
- Update Flutter web build to enable the web app publishing
=> fix: flutter web build

Earthfile, actions/run/action.yml, actions/run/dist/index.js, actions/run/src/run.test.ts, actions/run/src/run.ts
=> feat: exposes github token to run action

earthly/rust/stdcfgs/deny.toml, examples/rust/deny.toml, utilities/dbviz/deny.toml
=> feat(rust): Changes required for the chain-follower to pass CI.

earthly/flutter/Earthfile, earthly/flutter/installer/Earthfile
- invalidate cache for Google Chrome installation
=> fix: cache

earthly/rust/Earthfile, earthly/rust/stdcfgs/rust-toolchain.toml, earthly/rust/tools/Earthfile, examples/rust/rust-toolchain.toml, utilities/dbviz/rust-toolchain.toml
Also:
* add targets ready for cross compilation
* bump tool versions to latest
=> feat(rust): Bump rust to 1.81

earthly/cspell/Earthfile
Cspell needs to be easy readable to find issues fast.
Fixes #288
Minimize spell check output to errors only and fail-fast if one is picked up.
=> chore(ci): cspell improve error readability

.config/dictionaries/project.dic, earthly/playwright/Earthfile
Partially resolves #790
Added a function for setting up Playwright
There are no breaking changes
There are no applicable screenshots
=> chore(ci): Adding Playwright function

earthly/flutter/Earthfile, earthly/flutter/installer/Earthfile
Adds a reliable version number to browser artifacts required by the flutter builder.
=> fix(cat-ci): Flutter broken CI cache

actions/run/dist/index.js, actions/run/src/run.test.ts, actions/run/src/run.ts
=> fix: uses correct input name for gh token

earthly/playwright/Earthfile
=> chore(ci): update playwright version

earthly/docs/Earthfile
Local preview docs helper targets.
=> feat(docs): Add targets to help making local preview docs easier.

earthly/python/Earthfile
Pinning poetry version so ci doesnt brake for poetry updates
=> fix: Pin poetry version

earthly/flutter/Earthfile
This PR fixes flutter base image
=> fix: Flutter base image

earthly/postgresql/sql/setup-db.sql, utilities/scripts/bash/db_ops.sh, utilities/scripts/python/db_ops.py
=> fix: adjusts migration setup to work with AWS RDS

earthly/flutter/Earthfile, earthly/flutter/installer/Earthfile
Fix installing Chrome x64 in Flutter setup.
-
- fixed failing Chrome installation
- bumped Chrome to 132 (it's released in storage as branch R0002)
- use new R0002 in Flutter setup step
=> chore: fix installing Chrome x64 in Flutter setup

earthly/flutter/Earthfile, examples/flutter/example/pubspec.lock, examples/flutter/example/pubspec.yaml
Updates flutter version to 3.27.3
Needed by https://github.com/input-output-hk/catalyst-voices/pull/1775
=> chore: upgrade flutter to 3.27.3

.config/dictionaries/project.dic, earthly/flutter/Earthfile, examples/flutter/example/.gitignore, examples/flutter/example/ios/Flutter/Debug.xcconfig, examples/flutter/example/ios/Flutter/Release.xcconfig, examples/flutter/example/ios/Podfile, examples/flutter/example/macos/Flutter/Flutter-Debug.xcconfig, examples/flutter/example/macos/Flutter/Flutter-Release.xcconfig, examples/flutter/example/macos/Podfile, examples/flutter/example/macos/Podfile.lock, examples/flutter/example/macos/Runner.xcodeproj/project.pbxproj, examples/flutter/example/macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme, examples/flutter/example/macos/Runner.xcworkspace/contents.xcworkspacedata, examples/flutter/example/macos/Runner/AppDelegate.swift, examples/flutter/example/pubspec.lock, examples/flutter/example/pubspec.yaml
Updates flutter version to 3.29.0
Needed by: https://github.com/input-output-hk/catalyst-voices/pull/1844
=> chore: upgrade flutter to 3.29.0

earthly/rust/Earthfile, earthly/rust/stdcfgs/rust-toolchain.toml, earthly/rust/tools/Earthfile, examples/rust/rust-toolchain.toml
Bump rustc version to 1.85.
Bump `cargo-deny` to `0.18.0`.
=> feat(rust): Bump rustc version to 1.85

earthly/rust/tools/Earthfile, examples/flutter/example/pubspec.lock, examples/flutter/example/pubspec.yaml, examples/flutter/example/rust/Cargo.toml
Revert bumping `flutter_rust_bridge` from `2.9.0` to `2.5.1`
=> fix(rust): Downgrade `flutter_rust_bridge` to `2.5.1`

.gitignore, earthly/flutter/Earthfile
Adds optional argument for uploading debug symbols to sentry while building an app
Part of [#2830](https://github.com/input-output-hk/catalyst-voices/issues/2830)
- https://github.com/input-output-hk/catalyst-voices/pull/2851
=> feat: upload flutter debug symbols

earthly/flutter/installer/Earthfile
=> chore(test): edgedriver url changed fix

.config/dictionaries/project.dic, .github/workflows/dogfood.yml, blueprint.cue, docs/blueprint.cue, earthly/bash/blueprint.cue, earthly/cassandra/blueprint.cue, earthly/cspell/blueprint.cue, earthly/flutter/blueprint.cue, earthly/go/blueprint.cue, earthly/java/blueprint.cue, earthly/mdlint/blueprint.cue, earthly/playwright/blueprint.cue, earthly/postgresql/blueprint.cue, earthly/python/blueprint.cue, earthly/rust/blueprint.cue, earthly/spectral/blueprint.cue, earthly/wasm/c/blueprint.cue, examples/go/blueprint.cue, examples/postgresql/blueprint.cue, examples/python/blueprint.cue, examples/rust/blueprint.cue, examples/wasm/c/blueprint.cue, utilities/cql-to-d2/blueprint.cue, utilities/earthly-cache-watcher/blueprint.cue, utilities/fetcher/blueprint.cue, utilities/jorm-metrics-server/blueprint.cue
=> ci(general): bumps forge to v0.19.1 and ci to v1.8.1

earthly/flutter/Earthfile, earthly/flutter/installer/Earthfile
- Fixes issues git update dependencies for browser installers
- re enables tests
=> fix: chrome installer and reenable tests

.github/labels.yml
=> ci(general): add no-track label

utilities/jorm-metrics-server/jorm_metrics_server/models/active_plans.py, utilities/jorm-metrics-server/jorm_metrics_server/scraper.py
revert changes from https://github.com/input-output-hk/catalyst-ci/pull/461 and fix ruff checks
Most changes related to https://docs.astral.sh/ruff/rules/non-pep604-annotation-optional/
=> fix: ruff checks
