- earthly/cspell/Readme.md
- earthly/mdlint/Readme.md
Correct documentation for `mdlint` and `cspell` UDCs to use the correct UDC name.
> Fix names of example UDCs to match real UDCs

- actions/discover/dist/index.js
- actions/discover/src/discover.test.ts
- actions/discover/src/discover.ts
- fix: don't run discover action twice
- chore: cleanup discover action test
- chore: package
> chore: cleans up actions

- earthly/rust/Earthfile
- earthly/rust/config.toml
Close https://github.com/input-output-hk/catalyst-ci/issues/53
- fixed aarch64-unknown-linux-gnu rustflags, to solve an issue with cargo-nextest build, disable `target-feature=+crt-static` flag
- updated rust Earthly targets, added `with_cargo_nextest`, `with_cargo_chef`, `with_kani`, `with_refinery` and `with_cargo_machete` earthly arguuments, so it is possible to conditionally install these tools.
- fixed following issues on the `aarch64-unknown-linux-gnu` when eathly rust targets are runned on the macOS M1:
```
cannot produce proc-macro for `async-trait v0.1.74` as the target `aarch64-unknown-linux-gnu` does not support these crate types
```
```
Error: Kani does not support this platform (Rust target aarch64-unknown-linux-gnu)
```
> Updated aarch64-unknown-linux-gnu rustflags, updated rust Earthly targets

- earthly/postgresql/Earthfile
- earthly/postgresql/entry.sh
- earthly/postgresql/example/docker-compose.yml
- earthly/utils/Earthfile
- earthly/utils/README.md
- earthly/utils/assert.sh
Close #67
- Added 4 test cases of the integration tests for the PostgreSQL builder
- Cleanup entry.sh script
- Added utils dir for the Earthly utility stuff, added assert bash scripts, which are used to validate returned data from the db in Earthly targets
> feat: Add integration tests for PostgreSQL builder

- .github/workflows/ci.yml
- .github/workflows/run.yml
- actions/run/action.yml
- actions/run/dist/index.js
- actions/run/src/run.test.ts
- actions/run/src/run.ts
It is needed to pass `-P` flag to earthly during tests running to fix the following issue https://github.com/input-output-hk/catalyst-ci/actions/runs/6733556300/job/18302659923
> fix: Add -P flag for earhtly `test` CI runner

- earthly/rust/stdcfgs/clippy.toml
- examples/rust/clippy.toml
Modifing clippy lint to allow only expect in tests instead of unwrap. This should force testers to better comment their code
> fix: Allow_expect instead of allow _unwrap

- earthly/cspell/Earthfile
- earthly/rust/Earthfile
Remove `CP_SRC` UDC is a redundant command that could be replaced by the common `COPY` command.
> e.g., Closes #110
* Removed `CP_SRC` UDC
* Removed `cspell-test` as it won't be used by other dependencies.
> chore: remove `CP_SRC` UDC

- earthly/rust/stdcfgs/deny.toml
- examples/rust/deny.toml
Adds `BlueOak-1.0.0` license to the allowlist in `deny.toml`.
https://github.com/input-output-hk/hermes/pull/33
> chore: allow Blue Oak license

- docs/src/guides/languages/rust.md
- earthly/rust/scripts/std_build.sh
- earthly/rust/stdcfgs/cargo_config.toml
- examples/rust/.cargo/config.toml
Adding a new target `testunit` for running  only the unit tests and using it instead of the `testci` one in the build script
Leaving `testci` as it is at the moment but in the future we probably want to only target a subset of tests with it
> feat: Unit test alias

- earthly/rust/Earthfile
- earthly/rust/scripts/std_build.sh
- earthly/rust/stdcfgs/cargo_config.toml
- examples/rust/.cargo/config.toml
- examples/rust/Earthfile
Adding a UNIT_TEST UDC . This UDC will run unit tests and produce code coverage info using [LLVM instrumentation-based coverage](https://doc.rust-lang.org/rustc/instrument-coverage.html) with the help of [cargo-llvm-cov](https://github.com/taiki-e/cargo-llvm-cov) that supports nextest. The code coverage info will be printed on the stout after the test results as a support for the devs and will be also saved as an artifact to be used in CI.
Nextest will also create a test report in junit format that can be saved as artifact and used in CI.
The unit test alias and the testci alias have been removed as they will be substitute with a earthly target
> feat: UNIT_TEST UDC

- earthly/docs/poetry.lock
- earthly/docs/pyproject.toml
Bump mkdocs and dependent library versions to current latest.
Docs built with these versions here: https://input-output-hk.github.io/catalyst-ci/branch/feat_mkdocs_version_bump/
> docs(docs): Bump mkdocs and dependent library versions to current latest

- .github/workflows/ci.yml
> fix: makes building docs optional

- actions/run/dist/index.js
- actions/run/src/run.test.ts
- actions/run/src/run.ts
Fixing target flags being parsed after the target leading to errors like this https://github.com/input-output-hk/catalyst-artifacts/actions/runs/7478641429/job/20354035906#step:7:39
Moved target flags parsing after target
> fix: Move target flags after target

- cli/pkg/scanners/file_scanner.go
- cli/pkg/scanners/file_scanner_test.go
- docs/src/onboarding/index.md
allow target to have multiple hyphenated alphanumeric sequence
- Add test case for `target-test-test2` and `target-test-test3`
- Fix doc
- Fix regex to allow multiple hyphenated alphanumeric sequence
> fix: allow target to have multiple hyphenated alphanumeric sequence

- Earthfile
- cli/Earthfile
- docs/src/appendix/earthly.md
- docs/src/architecture/09_architecture_decisions/0001-arch-std.md
- docs/src/architecture/09_architecture_decisions/0002-adr.md
- docs/src/architecture/09_architecture_decisions/0003-language.md
- docs/src/architecture/09_architecture_decisions/0004-spelling.md
- docs/src/architecture/09_architecture_decisions/0005-rust.md
- docs/src/architecture/09_architecture_decisions/0006-rust-cargo-lock.md
- docs/src/architecture/09_architecture_decisions/0007-minimum-rust-version-supported.md
- docs/src/guides/languages/bash.md
- docs/src/guides/languages/go.md
- earthly/bash/Earthfile
- earthly/docs/Earthfile
- earthly/docs/common/overrides/cip.html
- earthly/postgresql/Earthfile
- earthly/python/Earthfile
- earthly/rust/Earthfile
- earthly/rust/scripts/std_build.py
- earthly/rust/stdcfgs/deny.toml
- examples/go/Earthfile
- examples/rust/deny.toml
- tools/fetcher/Earthfile
- tools/updater/Earthfile
- utilities/dbviz/deny.toml
Bumps all Rust tooling versions to latest.
Bumps all possible Alpine OS Containers to 3.19.
* `nginx` does not have an Alpine 3.19 container so it was not bumped.
* `dind` does not have an Alpine 3.19 container so it was not bumped.
Fixes a docs issue with CIP headers.
Updates how the Rust dependency graphs are generated to track changes in the upstream tool cli.
* Closes #171
* Closes #176
* Closes #181
> chore(ci): Bump Rust Versions & Alpine Versions, add ADR for rust-versions

- earthly/rust/Earthfile
Added [`cargo-expand`](https://github.com/dtolnay/cargo-expand) tool into the Rust builder
> feat: Add `cargo-expand` to the Rust builder

- earthly/rust/stdcfgs/deny.toml
- examples/rust/deny.toml
- utilities/dbviz/deny.toml
Unable to pass cargo deny without the following. Problems came about after adding `cardano-follower` dependency.
We don't have versioning on the cardano-follower hence wildcard issue. Plus we need to whitelist hermes git repo.
> build(cargo deny): allow

- .config/dictionaries/project.dic
- earthly/docs/Earthfile
- earthly/python/Earthfile
- earthly/rust/Earthfile
Downgrade an alpine version to `3.18` for `rust-base`. 
We have encountered a problems with using `libgcc:13` which goes with `alpine:3.19`.
fixes https://github.com/input-output-hk/hermes/pull/109
> fix: Downgrade rust-base alpine version to 3.18

- .github/workflows/branch-pages-delete.yml
- .github/workflows/pages.yml
This PR fixes two issues with the test reporting. It prevents the action that deploys the github pages from deleting the test report folder and it adds the test reports generated for the banch to the list of folders deleted when the branch is deleted
Fix https://github.com/input-output-hk/catalyst-voices/issues/326
Fix https://github.com/input-output-hk/catalyst-voices/issues/291
> fix: Test reports bugs

- earthly/python/Earthfile
Updated python builder, install `rich` dependency which are used by our builder scripts 
needed for: https://github.com/input-output-hk/catalyst-voices/pull/341
> feat: Python builder, install `rich`

- earthly/rust/Earthfile
Downgrade `cargo-deny` to `v0.14.10` from failed `v0.14.17`.
Here is the log of failure `v0.14.17` version.
https://github.com/EmbarkStudios/cargo-deny/pull/638
```sh
./e/rust+rust-base *failed* |    Compiling cargo-deny v0.14.17
./e/rust+rust-base *failed* | error[E0308]: arguments to this function are incorrect
./e/rust+rust-base *failed* |    --> /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/cargo-deny-0.14.17/src/advisories/helpers/db.rs:259:30
./e/rust+rust-base *failed* |     |
./e/rust+rust-base *failed* | 259 |         let remote_head_id = tame_index::utils::git::write_fetch_head(&repo, &outcome, &remote)
./e/rust+rust-base *failed* |     |                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ -----  --------  ------- expected `Remote<'_>`, found …
```
> fix: Downgrade cargo-deny version from failed cargo-deny `v0.14.17`

- earthly/rust/stdcfgs/deny.toml
- examples/rust/deny.toml
- utilities/dbviz/deny.toml
Updated `deny.toml` file, allowed "https://github.com/input-output-hk/catalyst-pallas.git" repo.
Needed for https://github.com/input-output-hk/hermes/pull/189
> fix: Add "https://github.com/input-output-hk/catalyst-pallas.git" to deny.toml

- earthly/rust/scripts/std_build.py
Add --verbose flag to rust builds so we can actually see what the build is doing.
> feat(rust): Add verbose option to rust standard build

- earthly/rust/Earthfile
Add a `--locked` flag to all rust builder tooling installation, to eliminate an issue of unexpected usage of broken libs by to the tolling
> fix: Fix  Rust builder tooling

- Earthfile
- cli/Earthfile
- docs/Earthfile
- earthly/bash/Earthfile
- earthly/docs/Earthfile
- earthly/postgresql/Earthfile
- earthly/python/Earthfile
- earthly/rust/Earthfile
- earthly/rust/scripts/std_build.py
- earthly/rust/stdcfgs/rust-toolchain.toml
- earthly/rust/tools/Earthfile
- earthly/wasm/c/Earthfile
- examples/go/Earthfile
- examples/postgresql/Earthfile
- examples/python/Earthfile
- examples/rust/.gitignore
- examples/rust/Earthfile
- examples/rust/rust-toolchain.toml
- examples/wasm/c/Earthfile
- tools/fetcher/Earthfile
- tools/updater/Earthfile
- utilities/dbviz/Earthfile
- utilities/dbviz/rust-toolchain.toml
- utilities/scripts/python/vendor_files_check.py
Updates to improve-rust-builder PR
> fix(rust-builders): Improve rust builder

- earthly/rust/stdcfgs/deny.toml
- examples/rust/deny.toml
- utilities/dbviz/deny.toml
- Added https://github.com/aldanor/hdf5-rust repo to the deny.toml allowance list.
- Added new license `ISC` needed with the dep of the hdf5  https://github.com/nagisa/rust_libloading
Needed for https://github.com/input-output-hk/hermes/pull/238
> feat: Add hdf5 git repo to deny allow list

- earthly/rust/Earthfile
- earthly/rust/stdcfgs/deny.toml
- examples/rust/deny.toml
- utilities/dbviz/deny.toml
- Added necessary tooling for static compilation of `hdf5` lib.
- Update `deny.toml` files to fix licence issues with `hdf5` crate.
Needed for https://github.com/input-output-hk/hermes/pull/239
> feat: Update Rust builder with hdf5 needed tools, update deny.toml files

- earthly/rust/Earthfile
- earthly/rust/scripts/std_checks.py
Fixing rust builder cargo `.config.toml` file check.
needed for https://github.com/input-output-hk/hermes/pull/241
> fix: Rust build

- earthly/rust/stdcfgs/cargo_manifest/project.toml
- earthly/rust/stdcfgs/cargo_manifest/workspace.toml
- examples/rust/Cargo.toml
- utilities/dbviz/Cargo.toml
Updated our cargo manifest templates to fix the following issue  https://rust-lang.github.io/rust-clippy/master/index.html#/lint_groups_priority.
https://github.com/input-output-hk/catalyst-voices/pull/518
> fix: Fixes 

- earthly/flutter/Earthfile
Adding command to save flutter coverage folder
> feat: adds flutter coverage

- earthly/rust/stdcfgs/cargo_manifest/project.toml
- earthly/rust/stdcfgs/cargo_manifest/workspace.toml
- earthly/rust/stdcfgs/clippy.toml
- examples/rust/Cargo.toml
- examples/rust/clippy.toml
- utilities/dbviz/Cargo.toml
- utilities/dbviz/clippy.toml
Updated rust clippy lints definitions:
- allowed to `unwrap` in tests.
- added new lint `todo = "deny`
- added new lint `unimplemented = "deny`
> feat: Modify rust clippy lints

- earthly/rust/stdcfgs/clippy.toml
- examples/rust/clippy.toml
- utilities/dbviz/clippy.toml
Added rust clippy  option `allow-expect-in-tests = true` 
needed for https://github.com/input-output-hk/hermes/pull/323
> feat: Rust clippy  option `allow-expect-in-tests = true` 

- earthly/rust/Earthfile
- examples/rust/crates/foo/src/lib.rs
Enabled Rust backtrace when something panics.
Setting up `RUST_BACKTRACE` env var inside `rust-base`.
https://github.com/input-output-hk/hermes/pull/323
> feat: Enables rust backtrace for earthly rust builder

- actions/build/action.yml
Causes GITHUB_TOKEN to be supplied to earthly so it can be used by targets, as a secret.
> feat(cat-ci): Add GITHUB_TOKEN as a secret when earthly is invoked.

- docs/mkdocs.yml
- docs/src/appendix/examples/latex.md
- earthly/docs/common/javascript/mathjax.js
- earthly/docs/common/std-theme.yml
Allowing [LaTex](https://www.latex-project.org) mathematical equations formatting for MkDocs pages.
Inside `.md` files it is possible to use some of the LaTex entities to nicely represent math equations like this
```Latex
\begin{equation}
f = \frac{1}{2}
\end{equation}
```
will be shown as 
docs example [section](https://input-output-hk.github.io/catalyst-ci/branch/feat_docs_latex/appendix/examples/latex/)
> feat: Enable LaTex mathematical equations format for MkDocs

- Earthfile
- docs/src/appendix/earthly.md
- docs/src/guides/languages/bash.md
- docs/src/guides/languages/go.md
- earthly/bash/Earthfile
- earthly/docs/Earthfile
- earthly/postgresql/Earthfile
- examples/go/Earthfile
Fix for CI broken by upstream Alpine containers disappearing
> fix(cat-ci): Pin alpine versions to try and stop containers disappearing on upstream updates

- earthly/flutter/Earthfile
Defers the error that can be raised after running flutter unit tests until the test_reports and coverage artifacts are saved, then raises an error to indicate that the target failed.
- `flutter test` does not generate any test_reports therefore I'm removing the artifacts
> fix(earthly-flutter): Make sure earthly target fails when flutter tests fail

- earthly/rust/scripts/std_build.py
- earthly/rust/stdcfgs/cargo_config.toml
- examples/rust/.cargo/config.toml
- examples/rust/crates/foo/benches/benchmark.rs
Updated our cargo aliases `testunit` and `testcov` by disabling running benchmarks in these runs.
Added additional flags as `--all-targets` and `--no-fail-fast` for `cargo_bench` function.
Related PR https://github.com/input-output-hk/catalyst-libs/pull/65
> feat(rust): Update disable running benchmarks with `nextest` and `llvm-cov`

- earthly/rust/scripts/std_checks.py
- earthly/rust/stdcfgs/deny.toml
- examples/rust/deny.toml
- Removed all RUST-SEC exceptions from `deny.toml`.
- Made `unmaintained` advisories issues as warnings.
- Added new git repos into the `allow-git` list.
Needed for this PR https://github.com/input-output-hk/catalyst-libs/pull/68
> feat(rust): Update `deny.toml` config, make `unmaintained` as warnings

- earthly/cddl/Earthfile
Added a new `cddl-base` target with installing [cddlc](https://github.com/cabo/cddlc) tool to validate `.cddl` files.
Needs for https://github.com/input-output-hk/catalyst-libs/pull/79
> feat: Add `cddl-base` target

- earthly/docs/Earthfile
- earthly/flutter/Earthfile
Flutter prints warnings when called by root user but it can be fixed just by adding CI env. This PR addresses it.
Before
```bash
+check-static-analysis | Analyzing catalyst_analysis...
+check-static-analysis | No issues found!
+check-static-analysis | catalyst_analysis: SUCCESS
+check-static-analysis | --------------------------------------------------------------------------------
+check-static-analysis | catalyst_cardano:
+check-static-analysis | ERROR:    Woah! You appear to be trying to run flutter as root.
+check-static-analysis |    We strongly recommend running the flutter tool without superuser privileges.
+check-static-analysis |   /
+check-static-analysis | 📎
+check-static-analysis | Analyzing catalyst_cardano...
+check-static-analysis | No issues found!
+check-static-analysis | …
```
> feat(flutter): add CI env var

- earthly/rust/stdcfgs/rustfmt.toml
- examples/rust/rustfmt.toml
In Poem, doc attributes prevent Poem from picking up the doc comment, and it then reverts to the documentation in the underlying type.
This is very useful for enforcing consistent documentation.
So, prevent doc attributes being converted to actual doc comments.
> fix(docs):  Don't convert doc attributes to doc comments on format.

- earthly/rust/stdcfgs/clippy.toml
- examples/rust/clippy.toml
- utilities/earthly-cache-watcher/main.py
This pull request adds `allow-panic-in-tests = true` to the `clippy.toml` config.
It is ok to panic in the tests and we already allow the usage of both `unwrap` and `expect` (`allow-unwrap-in-tests` and `allow-expect-in-tests`). Sometimes it is easier to use a direct `panic!()` call. For example:
```rust
let Address::Stake(address) = cip0134_uri.address() else {
panic!("Unexpected address type ({uri})");
};
```
Rewriting this code to use `unwrap` is possible, but more cumbersome.
I have encountered this issue working on the https://github.com/input-output-hk/catalyst-libs/pull/102 pull request.
> feat(rust): Add 'allow-panic-in-tests = true' to the Clippy config

- earthly/rust/Earthfile
- earthly/rust/stdcfgs/deny.toml
- earthly/rust/stdcfgs/rust-toolchain.toml
- examples/rust/deny.toml
- examples/rust/rust-toolchain.toml
> fix(rust): Bump compiler to latest release

- earthly/postgresql/Earthfile
- **fix: don't save image in Earthly functions**
- **chore: adds image tag argument**
- **wip: defaults image tag argument**
> fix: adds tag argument to psql BUILD function

- earthly/rust/stdcfgs/deny.toml
- examples/rust/deny.toml
Allow for cargo deny "https://github.com/orxfun/orx-pseudo-default" as source. Needed for https://github.com/input-output-hk/catalyst-voices/pull/1808
> feat(rust): Allow "https://github.com/orxfun/orx-pseudo-default" as source

- .config/dictionaries/project.dic
- earthly/flutter/Earthfile
Installs `sqllite` 
Drift `sqllite` database was added in [1789](https://github.com/input-output-hk/catalyst-voices/pull/1789) with unit tests which are running locally in CI. 
Those tests require `sqllite` to be installed.
Unlocks https://github.com/input-output-hk/catalyst-voices/pull/1789
> feat: install sqlite for flutter

- earthly/rust/stdcfgs/deny.toml
- examples/rust/deny.toml
Removed unneeded  `orx-pseudo-default` cargo deny exception.
> feat(rust): Remove unneeded `orx-pseudo-default` cargo deny exception

- earthly/flutter/Earthfile
Explicitly sets set arm64 flutter source as HTTPS because otherwise docker may attempt using SSH
> fix: explicit https flutter fetch

- earthly/docs/Earthfile
- earthly/python/Earthfile
Move a base image for `python-base` form alpine to debian to be compatible with the `rust-base`.
Needed for https://github.com/input-output-hk/catalyst-voices/pull/1906
> feat(python): Change python-base image from alpine to debian

- earthly/go/Earthfile
Ginko [v2.23.0](https://github.com/onsi/ginkgo/releases/tag/v2.23.0) needs go version 1.23.0 while we are running go 1.22.4. This PR pins ginko to version 2.22.2 so we dont need to upgrade go 
> fix: ginko version

- earthly/flutter/Earthfile
- earthly/flutter/installer/Earthfile
This PR adds a target to run web tests on flutter and a function to create a patched chrome to overwrite the parameters that flutter passes to chrome
> test: adds flutter web unit tests

- earthly/flutter_rust_bridge/Earthfile
- earthly/rust/tools/Earthfile
- examples/flutter/example/pubspec.lock
- examples/flutter/example/pubspec.yaml
- examples/flutter/example/rust/Cargo.toml
Fixing a raising issue of `wasm32-unknown-unknown`  for the `flutter_rust_bridge`
https://github.com/rust-lang/rust/issues/138762
> fix(flutter_rust_bridge): WASM compilation issue for `flutter_rust_bridge`

- earthly/flutter/Earthfile
- examples/flutter/example/pubspec.lock
- examples/flutter/example/pubspec.yaml
- Reverts flutter installer workaround on arm64 target as the [original issue](https://github.com/flutter/flutter/issues/162251) is fixed now and released in flutter [3.29.3](https://github.com/flutter/flutter/blob/master/CHANGELOG.md#3293).
- Reverted workaround thath caused issues such as: [#2328](https://github.com/input-output-hk/catalyst-voices/issues/2328)
- Bump minimum dart version to 3.7.0, it is bundled with flutter >= 3.29.x
- Bump minimum flutter version to 3.29.3
Refers [#2328](https://github.com/input-output-hk/catalyst-voices/issues/2328)
> chore(flutter): upgrade flutter to 3.29.3, revert arm64 flutter installer workaround

- earthly/rust/stdcfgs/deny.toml
- examples/rust/deny.toml
Added `CDLA-Permissive-2.0` licence to the `cargo-deny` allowed list
> feat(rust): Allow `CDLA-Permissive-2.0` licence

- earthly/flutter_rust_bridge/Earthfile
This PR removes the workaround for the rust wasm code gen
https://blog.rust-lang.org/2025/04/04/c-abi-changes-for-wasm32-unknown-unknown/
> fix: rust wasm codegen

- earthly/rust/tools/Earthfile
Matches the supposed bump in Hermes.
Hermes integration tests temporarily all go down.
[hermes/#432](https://github.com/input-output-hk/hermes/pull/432)
> chore(earthly/rust): bump wit-bindgen to 0.43

- earthly/rust/stdcfgs/rustfmt.toml
- examples/rust/crates/bar/src/lib.rs
- examples/rust/crates/foo/src/lib.rs
- examples/rust/rustfmt.toml
This PR reverts the changes to the rust formatter configuration as it is too cumbersome to fix the formatting in all open PRs. We'll "revert this revert" once the big feature branches are merged.
> chore(rust): Revert Rust fmt changes

- utilities/project-fields-validator/main.py
Remove "end" from the list of project required fields because it cannot be set reliably during the pull request creation.
> chore(general): Remove 'end' from the list of project required fields

- .github/workflows/update-catalyst-ci-deps.yml
- add update catalyst ci  deps workflow
> [!NOTE]
> I tested it locally. It should do the following
>   - Branch: chore/update-catalyst-ci-to-2.1.0
>  - PR Title: Update catalyst-ci to v2.1.0
> - PR Body: Update catalyst-ci to v2.1.0. Release: https://github.com/input-output-hk/catalyst-ci/releases/tag/v2.1.0
> ci(general): add update catalyst ci  deps workflow
